export const localityNames = {
  'loc-electronic-city': 'Electronic City',
  'loc-btm-layout': 'BTM Layout',
  'loc-marathahalli': 'Marathahalli',
  'loc-hebbal': 'Hebbal',
  'loc-whitefield': 'Whitefield',
  'loc-koramangala': 'Koramangala',
  'loc-indiranagar': 'Indiranagar',
  'loc-hsr-layout': 'HSR Layout',
  'loc-jayanagar': 'Jayanagar',
  'loc-jp-nagar': 'JP Nagar',
  'loc-malleshwaram': 'Malleshwaram',
  'loc-rajajinagar': 'Rajajinagar',
  'loc-yelahanka': 'Yelahanka',
  'loc-banashankari': 'Banashankari',
  'loc-yeshwanthpur': 'Yeshwanthpur',
  'loc-rt-nagar': 'RT Nagar',
  'loc-peenya': 'Peenya Industrial Area',
};
